title: Joel's whiteboard
email: joel@valkyrnstudios.net
description: >-
  A blog-like location for motorcycles, tech, and gaming articles
baseurl: ""
url: ""

theme: minimal-mistakes-jekyll
plugins:
  - jekyll-include-cache
  - jekyll-gist

minimal_mistakes_skin: "dark"
repository: "joelgarboden/joelgarboden.github.io"
search: true
permalink: /:categories/:title/
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
