source "https://rubygems.org"
gem "jekyll", "~> 3.9.0"
gem "github-pages", "~> 209", group: :jekyll_plugins

group :jekyll_plugins do
  gem "jekyll-gist"
  gem "jekyll-include-cache"
end

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]
